/*
Nefarious Motorsports ME7 ECU Flasher
Copyright (C) 2017  Nefarious Motorsports Inc

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Contact by Email: tony@nefariousmotorsports.com
*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;
using System.Threading;
using System.Runtime.Remoting.Messaging;
using System.Diagnostics;
using System.ComponentModel;
using System.Xml.Serialization;

using Shared;

namespace Communication
{
    public class KWP2000DTCInfo
    {
		public ushort DTC { get; set; }
		public byte Status { get; set; }
    };

    [Flags]
    public enum KWP2000DTCStatus : byte
    {
		//I think the user may only need to see the messages for bits that are set. Need to double check the flow chart to investigate more.

        [ValueMappedDescriptionAttribute(true, "Pending fault currently present")]
        [ValueMappedDescriptionAttribute(false, "Pending fault not currently present")]
        PendingFaultPresent = 0x01,//This bit indicates that the fault indicated by this DTC is currently present in the server (ECU).
        [ValueMappedDescriptionAttribute(true, "Pending fault was present during the current driving cycle")]
        [ValueMappedDescriptionAttribute(false, "Pending fault was not present during this driving cycle")]
        PendingFaultState = 0x02,//This bit indicates that the pending fault indicated by this DTC has been present (bit 0 has been set) at least once during the current driving cycle.
        [ValueMappedDescriptionAttribute(true, "Fault test is running")]
        [ValueMappedDescriptionAttribute(false, "Fault test is not running")]
        TestRunning = 0x04,//This bit indicates whether the diagnostic trouble code test conditions are met at the time of request.
        [ValueMappedDescriptionAttribute(true, "Fault test is currently inhibited due to another fault being present")]
        [ValueMappedDescriptionAttribute(false, "Fault test is not currently inhibited by another fault being present")]
        TestInhibit = 0x08,//This bit indicates that the diagnostic trouble code test conditions are not met because of another fault in the server (ECU).
        [ValueMappedDescriptionAttribute(true, "Fault test has not been completed")]
        [ValueMappedDescriptionAttribute(false, "Fault test has been completed")]
        TestReadiness = 0x10,//This bit indicates that the diagnostic trouble code test has not yet been completed during the current driving cycle.
        [ValueMappedDescriptionAttribute(true, "Fault has been validated and stored")]
        [ValueMappedDescriptionAttribute(false, "Fault has not been validated and not stored")]
        DTCStorageState = 0x20,//This bit indicates that the fault indicated by this DTC has been validated (bit 6 has been set) at least once and stored in non volatile memory since this DTC was last cleared.
        [ValueMappedDescriptionAttribute(true, "Fault currently validated")]
        [ValueMappedDescriptionAttribute(false, "No validated fault present")]
        ValidatedFaultPresent = 0x40,//This bit indicates that the fault indicated by this DTC is currently validated in the server (ECU).
        [ValueMappedDescriptionAttribute(true, "Fault was validated during the current driving cycle")]
        [ValueMappedDescriptionAttribute(false, "Fault has not been validated during current driving cycle")]
        ValidatedFaultState = 0x80//This bit indicates that the fault indicated by this DTC has been validated (bit 6 has been set) at least once during the current driving cycle.
    };

    public class KWP2000VAGDTCDictionary
    {
        static KWP2000VAGDTCDictionary()
        {
            DTCStrings = new Dictionary<ushort, string>();

            PopulateDictionaryWithVAGCodes();
        }

        public static Dictionary<ushort, string> DTCStrings
        {
            get;
            private set;
        }

        private static void PopulateDictionaryWithVAGCodes()
        {
            DTCStrings.Add(0x0010, "-A- Camshaft Position Actuator Circuit Bank 1 Malfunction");
            DTCStrings.Add(0x0020, "-A- Camshaft Position Actuator Circuit Bank 2 Malfunction");
            DTCStrings.Add(0x0065, "Air Assisted Injector Control Range/Performance");
            DTCStrings.Add(0x0066, "Air Assisted Injector Control Low Input/Short to ground");
            DTCStrings.Add(0x0067, "Air Assisted Injector Control Input/Short to B+");
            DTCStrings.Add(0x0101, "Mass or Volume Air Flow Circuit Range/Performance");
            DTCStrings.Add(0x0102, "Mass or Volume Air Flow Circuit Low Input");
            DTCStrings.Add(0x0103, "Mass or Volume Air Flow Circuit High Input");
            DTCStrings.Add(0x0105, "Manifold Absolute Pressure or Barometric Pressure Voltage supply");
            DTCStrings.Add(0x0106, "Manifold Absolute Pressure or Barometric Pressure Range/Performance");
            DTCStrings.Add(0x0107, "Manifold Absolute Pressure or Barometric Pressure Low Input");
            DTCStrings.Add(0x0108, "Manifold Absolute Pressure or Barometric Pressure High Input");
            DTCStrings.Add(0x0112, "Intake Air Tempurature Circuit Low Input");
            DTCStrings.Add(0x0113, "Intake Air Tempurature Circuit High Input");
            DTCStrings.Add(0x0116, "Engine Coolant Tempurature Circuit Range/Performance");
            DTCStrings.Add(0x0117, "Engine Coolant Tempurature Circuit Low Input");
            DTCStrings.Add(0x0118, "Engine Coolant Tempurature Circuit High Input");
            DTCStrings.Add(0x0120, "Throttle/Pedal Position Sensor A Circuit Malfunction");
            DTCStrings.Add(0x0121, "Throttle/Pedal Position Sensor A Circuit Range/Performance");
            DTCStrings.Add(0x0122, "Throttle/Pedal Position Sensor A Circuit Low Input");
            DTCStrings.Add(0x0123, "Throttle/Pedal Position Sensor A Circuit High Input");
            DTCStrings.Add(0x0125, "Insufficient Coolant Tempurature for Closed Loop Fuel Control");
            DTCStrings.Add(0x0128, "Coolant Thermostat/Valve Temperature below control range");
            DTCStrings.Add(0x0130, "O2 Sensor Circuit Bank 1 Sensor 1 Malfunction");
            DTCStrings.Add(0x0131, "O2 Sensor Circuit Bank 1 Sensor 1 Low Voltage");
            DTCStrings.Add(0x0132, "O2 Sensor Circuit Bank 1 Sensor 1 High Voltage");
            DTCStrings.Add(0x0133, "O2 Sensor Circuit Bank 1 Sensor 1 Slow Response");
            DTCStrings.Add(0x0134, "O2 Sensor Circuit Bank 1 Sensor 1 No Activity Detected");
            DTCStrings.Add(0x0135, "O2 Sensor Heater Circuit Bank 1 Sensor 1 Malfunction");
            DTCStrings.Add(0x0136, "O2 Sensor Circuit Bank 1 Sensor 2 Malfunction");
            DTCStrings.Add(0x0137, "O2 Sensor Circuit Bank 1 Sensor 2 Low Voltage");
            DTCStrings.Add(0x0138, "O2 Sensor Circuit Bank 1 Sensor 2 High Voltage");
            DTCStrings.Add(0x0139, "O2 Sensor Circuit Bank 1 Sensor 2 Slow Response");
            DTCStrings.Add(0x0140, "O2 Sensor Circuit Bank 1 Sensor 2 No Activity Detected");
            DTCStrings.Add(0x0141, "O2 Sensor Heater Circuit Bank 1 Sensor 2 Malfunction");
            DTCStrings.Add(0x0150, "O2 Sensor Circuit Bank 2 Sensor 1 Malfunction");
            DTCStrings.Add(0x0151, "O2 Sensor Circuit Bank 2 Sensor 1 Low Voltage");
            DTCStrings.Add(0x0152, "O2 Sensor Circuit Bank 2 Sensor 1 High Voltage");
            DTCStrings.Add(0x0153, "O2 Sensor Circuit Bank 2 Sensor 1 Slow Response");
            DTCStrings.Add(0x0154, "O2 Sensor Circuit Bank 2 Sensor 1 No Activity Detected");
            DTCStrings.Add(0x0155, "O2 Sensor Heater Circuit Bank 2 Sensor 1 Malfunction");
            DTCStrings.Add(0x0156, "O2 Sensor Circuit Bank 2 Sensor 2 Malfunction");
            DTCStrings.Add(0x0157, "O2 Sensor Circuit Bank 2 Sensor 2 Low Voltage");
            DTCStrings.Add(0x0158, "O2 Sensor Circuit Bank 2 Sensor 2 High Voltage");
            DTCStrings.Add(0x0159, "O2 Sensor Circuit Bank 2 Sensor 2 Slow Response");
            DTCStrings.Add(0x0160, "O2 Sensor Circuit Bank 2 Sensor 2 No Activity Detected");
            DTCStrings.Add(0x0161, "O2 Sensor Heater Circuit Bank 2 Sensor 2 Malfunction");
            DTCStrings.Add(0x0170, "Fuel Trim Bank 1 Malfunction");
            DTCStrings.Add(0x0171, "Fuel Trim Bank 1 System too Lean");
            DTCStrings.Add(0x0172, "Fuel Trim Bank 1 System too Rich");
            DTCStrings.Add(0x0173, "Fuel Trim Bank 2 Malfunction");
            DTCStrings.Add(0x0174, "Fuel Trim Bank 2 System too Lean");
            DTCStrings.Add(0x0175, "Fuel Trim Bank 2 System too Rich");
            DTCStrings.Add(0x0182, "Fuel temperature sender-G81 Short to ground");
            DTCStrings.Add(0x0183, "Fuel temperature sender-G81 Interruption/Short to B+");
            DTCStrings.Add(0x0197, "Engine Oil Temperature Circuit Low Input");
            DTCStrings.Add(0x0198, "Engine Oil Temperature Circuit High Input");
            DTCStrings.Add(0x0201, "Cyl.1, Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0202, "Cyl.2, Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0203, "Cyl.3, Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0204, "Cyl.4, Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0205, "Cyl.5 Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0206, "Cyl.6 Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0207, "Cyl.7 Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0208, "Cyl.8 Injector Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0215, "Engine Shut-Off Solenoid Malfunction");
            DTCStrings.Add(0x0216, "Injector/Injection Timing Control Malfunction");
            DTCStrings.Add(0x0219, "Engine Overspeed Condition");
            DTCStrings.Add(0x0221, "Throttle Position Sensor -B- Circuit Range/Performance");
            DTCStrings.Add(0x0222, "Throttle Position Sensor -B- Circuit Low Input");
            DTCStrings.Add(0x0223, "Throttle Position Sensor -B- Circuit High Input");
            DTCStrings.Add(0x0225, "Throttle Position Sensor -C- Circuit Voltage supply");
            DTCStrings.Add(0x0226, "Throttle Position Sensor -C- Circuit Range/Performance");
            DTCStrings.Add(0x0227, "Throttle Position Sensor -C- Circuit Low Input");
            DTCStrings.Add(0x0228, "Throttle Position Sensor -C- Circuit Hight Input");
            DTCStrings.Add(0x0230, "Fuel Pump Primary Circuit Fault in electrical circuit");
            DTCStrings.Add(0x0234, "Turbocharger Overboost Condition Control limit exceeded");
            DTCStrings.Add(0x0235, "Turbocharger Boost Sensor (A) Circuit Control limit not reached");
            DTCStrings.Add(0x0236, "Turbocharger Boost Sensor (A) Circuit Range/Performance");
            DTCStrings.Add(0x0237, "Turbocharger Boost Sensor (A) Circuit Low Input");
            DTCStrings.Add(0x0238, "Turbocharger Boost Sensor (A) Circuit High Input");
            DTCStrings.Add(0x0243, "Turbocharger Wastegate Solenoid (A) Open/Short Circuit to Ground");
            DTCStrings.Add(0x0245, "Turbocharger Wastegate Solenoid (A) Low Input/Short to ground");
            DTCStrings.Add(0x0246, "Turbocharger Wastegate Solenoid (A) High Input/Short to B+");
            DTCStrings.Add(0x0252, "Injection Pump Metering Control (A) Range/Performance");
            DTCStrings.Add(0x0261, "Cyl.1 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0262, "Cyl.1 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0264, "Cyl.2 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0265, "Cyl.2 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0267, "Cyl.3 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0268, "Cyl.3 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0270, "Cyl.4 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0271, "Cyl.4 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0273, "Cyl.5 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0274, "Cyl.5 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0276, "Cyl.6 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0277, "Cyl.6 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0279, "Cyl.7 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0280, "Cyl.7 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0282, "Cyl.8 Injector Circuit Low Input/Short to ground");
            DTCStrings.Add(0x0283, "Cyl.8 Injector Circuit High Input/Short to B+");
            DTCStrings.Add(0x0300, "Random/Multiple Cylinder Misfire Detected");
            DTCStrings.Add(0x0301, "Cyl.1 Misfire Detected");
            DTCStrings.Add(0x0302, "Cyl.2 Misfire Detected");
            DTCStrings.Add(0x0303, "Cyl.3 Misfire Detected");
            DTCStrings.Add(0x0304, "Cyl.4 Misfire Detected");
            DTCStrings.Add(0x0305, "Cyl.5 Misfire Detected");
            DTCStrings.Add(0x0306, "Cyl.6 Misfire Detected");
            DTCStrings.Add(0x0307, "Cyl.7 Misfire Detected");
            DTCStrings.Add(0x0308, "Cyl.8 Misfire Detected");
            DTCStrings.Add(0x0313, "Misfire Detected Low Fuel Level");
            DTCStrings.Add(0x0314, "Single Cylinder Misfire");
            DTCStrings.Add(0x0321, "Ignition/Distributor Engine Speed Input Circuit Range/Performance");
            DTCStrings.Add(0x0322, "Ignition/Distributor Engine Speed Input Circuit No Signal");
            DTCStrings.Add(0x0325, "Knock Sensor 1 Circuit Electrical Fault in Circuit");
            DTCStrings.Add(0x0326, "Knock Sensor 1 Circuit Range/Performance");
            DTCStrings.Add(0x0327, "Knock Sensor 1 Circuit Low Input");
            DTCStrings.Add(0x0328, "Knock Sensor 1 Circuit High Input");
            DTCStrings.Add(0x0332, "Knock Sensor 2 Circuit Low Input");
            DTCStrings.Add(0x0333, "Knock Sensor 2 Circuit High Input");
            DTCStrings.Add(0x0335, "Crankshaft Position Sensor (A) Circuit Malfunction");
            DTCStrings.Add(0x0336, "Crankshaft Position Sensor (A) Circuit Range/Performance/Missing tooth");
            DTCStrings.Add(0x0337, "Crankshaft Position Sensor (A) Circuit Low Input");
            DTCStrings.Add(0x0340, "Camshaft Position Sensor (A) Circuit Incorrect allocation");
            DTCStrings.Add(0x0341, "Camshaft Position Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0342, "Camshaft Position Sensor Circuit Low Input");
            DTCStrings.Add(0x0343, "Camshaft Position Sensor Circuit High Input");
            DTCStrings.Add(0x0351, "Ignition Coil (A) Cyl.1 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0352, "Ignition Coil (B) Cyl.2 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0353, "Ignition Coil (C) Cyl.3 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0354, "Ignition Coil (D) Cyl.4 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0355, "Ignition Coil (E) Cyl.5 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0356, "Ignition Coil (F) Cyl.6 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0357, "Ignition Coil (G) Cyl.7 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0358, "Ignition Coil (H) Cyl.8 Primary/Secondary Circuit Malfunction");
            DTCStrings.Add(0x0380, "Glow Plug/Heater Circuit (A) Electrical Fault in Circuit");
            DTCStrings.Add(0x0400, "Exhaust Gas Recirculation Flow Malfunction");
            DTCStrings.Add(0x0401, "Exhaust Gas Recirculation Flow Insufficient Detected");
            DTCStrings.Add(0x0402, "Exhaust Gas Recirculation Flow Excessive Detected");
            DTCStrings.Add(0x0403, "Exhaust Gas Recirculation Control Circuit Malfunction");
            DTCStrings.Add(0x0404, "Exhaust Gas Recirculation Control Circuit Range/Performance");
            DTCStrings.Add(0x0405, "Exhaust Gas Recirculation Sensor (A) Circuit Low Input");
            DTCStrings.Add(0x0406, "Exhaust Gas Recirculation Sensor (A) Circuit High Input");
            DTCStrings.Add(0x0407, "Exhaust Gas Recirculation Sensor (B) Circuit Low Input");
            DTCStrings.Add(0x0408, "Exhaust Gas Recirculation Sensor (B) Circuit High Input");
            DTCStrings.Add(0x0410, "Secondary Air Injection System Malfunction");
            DTCStrings.Add(0x0411, "Secondary Air Injection System Incorrect Flow Detected");
            DTCStrings.Add(0x0412, "Secondary Air Injection System Switching Valve A Circuit Malfunction");
            DTCStrings.Add(0x0418, "Secondary Air Injection System Relay (A) Control Circuit Malfunction");
            DTCStrings.Add(0x0420, "Catalyst System,Bank 1 Efficiency Below Threshold");
            DTCStrings.Add(0x0422, "Main Catalyst Bank 1 Below Threshold");
            DTCStrings.Add(0x0427, "Catalyst Temperature Sensor Bank 1 Low Input/Short to ground");
            DTCStrings.Add(0x0428, "Catalyst Temperature Sensor Bank 1 High Input/Open/Short Circuit to B+");
            DTCStrings.Add(0x0432, "Main Catalyst Bank 2 Efficiency Below Threshold");
            DTCStrings.Add(0x0436, "Catalyst Temperature Sensor Bank 2 Range/Performance");
            DTCStrings.Add(0x0437, "Catalyst Temperature Sensor Bank 2 Low Input/Short to ground");
            DTCStrings.Add(0x0438, "Catalyst Temperature Sensor Bank 2 High Input/Open/Short Circuit to B+");
            DTCStrings.Add(0x0440, "EVAP Emission Control System Malfunction");
            DTCStrings.Add(0x0441, "EVAP Emission Control System Incorrect Purge Flow");
            DTCStrings.Add(0x0442, "EVAP Emission Control System (Small Leak) Leak Detected");
            DTCStrings.Add(0x0443, "EVAP Emission Control System Purge Valve Circuit Electrical Fault in Circuit");
            DTCStrings.Add(0x0452, "EVAP Emission Control System Pressure Sensor Low Input");
            DTCStrings.Add(0x0453, "EVAP Emission Control System Pressure Sensor High Input");
            DTCStrings.Add(0x0455, "EVAP Emission Control System (Gross Leak) Leak Detected");
            DTCStrings.Add(0x0461, "Fuel Level Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0462, "Fuel Level Sensor Circuit Low Input");
            DTCStrings.Add(0x0463, "Fuel Level Sensor Circuit High Input");
            DTCStrings.Add(0x0501, "Vehicle Speed Sensor Range/Performance");
            DTCStrings.Add(0x0503, "Vehicle Speed Sensor Intermittent/Erratic/High Input");
            DTCStrings.Add(0x0505, "Idle Control System Malfunction");
            DTCStrings.Add(0x0506, "Idle Control System RPM Lower than Expected");
            DTCStrings.Add(0x0507, "Idle Control System Higher than Expected");
            DTCStrings.Add(0x0510, "Closed Throttle Position Switch Malfunction");
            DTCStrings.Add(0x0531, "A/C Refrigerant Pressure Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0532, "A/C Refrigerant Pressure Sensor Circuit Low Input");
            DTCStrings.Add(0x0533, "A/C Refrigerant Pressure Sensor Circuit High Input");
            DTCStrings.Add(0x0551, "Power Steering Pressure Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0560, "System Voltage Malfunction");
            DTCStrings.Add(0x0562, "System Voltage Low Voltage");
            DTCStrings.Add(0x0563, "System Voltage High Voltage");
            DTCStrings.Add(0x0568, "Cruise Control Set Signal Incorrect Signal");
            DTCStrings.Add(0x0571, "Cruise/Brake Switch (A) Circuit Malfunction");
            DTCStrings.Add(0x0600, "Serial Communication Link (Data Bus) Message Missing");
            DTCStrings.Add(0x0601, "Internal Control Module Memory Check Sum Error");
            DTCStrings.Add(0x0602, "Control Module Programming Error/Malfunction");
            DTCStrings.Add(0x0603, "Internal Control Module (KAM) Error");
            DTCStrings.Add(0x0604, "Internal Control Module Random Access Memory (RAM) Error");
            DTCStrings.Add(0x0605, "Internal Control Module ROM Test Error");
            DTCStrings.Add(0x0606, "ECM/PCM Processor");
			DTCStrings.Add(0x0638, "Throttle Actuator Control Range/Performance");
            DTCStrings.Add(0x0642, "Knock Control Control Module Malfunction");
            DTCStrings.Add(0x0645, "A/C Clutch Relay Control Circuit");
            DTCStrings.Add(0x0650, "MIL Control Circuit Electrical Fault in Circuit");
            DTCStrings.Add(0x0654, "Engine RPM Output Circuit Electrical Fault in Circuit");
            DTCStrings.Add(0x0656, "Fuel Level Output Circuit Electrical Fault in Circuit");
			DTCStrings.Add(0x0686, "Engine Control Module Power Relay Control Circuit Low");
            DTCStrings.Add(0x0700, "Transmission Control System Malfunction");
            DTCStrings.Add(0x0702, "Transmission Control System Electrical");
            DTCStrings.Add(0x0703, "Torque Converter/Brake Switch B Circuit Malfunction");
            DTCStrings.Add(0x0705, "Transmission Range Sensor Circuit(PRNDL Input ) Malfunction");
            DTCStrings.Add(0x0706, "Transmission Range Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0707, "Transmission Range Sensor Circuit Low Input");
            DTCStrings.Add(0x0708, "Transmission Range Sensor Circuit High Input");
            DTCStrings.Add(0x0710, "Transmission Fluid Tempurature Sensor Circuit Malfunction");
            DTCStrings.Add(0x0711, "Transmission Fluid Tempurature Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0712, "Transmission Fluid Tempurature Sensor Circuit Low Input");
            DTCStrings.Add(0x0713, "Transmission Fluid Tempurature Sensor Circuit High Input");
            DTCStrings.Add(0x0715, "Input Turbine/Speed Sensor Circuit Malfunction");
            DTCStrings.Add(0x0716, "Input Turbine/Speed Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0717, "Input Turbine/Speed Sensor Circuit No Signal");
            DTCStrings.Add(0x0721, "Output Speed Sensor Circuit Range/Performance");
            DTCStrings.Add(0x0722, "Output Speed Sensor Circuit No Signal");
            DTCStrings.Add(0x0725, "Engine Speed Input Circuit Malfunction");
            DTCStrings.Add(0x0726, "Engine Speed Input Circuit Range/Performance");
            DTCStrings.Add(0x0727, "Engine Speed Input Circuit No Signal");
            DTCStrings.Add(0x0730, "Gear Incorrect Ratio");
            DTCStrings.Add(0x0731, "Gear 1 Incorrect Ratio");
            DTCStrings.Add(0x0732, "Gear 2 Incorrect Ratio");
            DTCStrings.Add(0x0733, "Gear 3 Incorrect Ratio");
            DTCStrings.Add(0x0734, "Gear 4 Incorrect Ratio");
            DTCStrings.Add(0x0735, "Gear 5 Incorrect Ratio");
            DTCStrings.Add(0x0740, "Torque Converter Clutch Circuit Malfunction");
            DTCStrings.Add(0x0741, "Torque Converter Clutch Circuit Performance or Stuck Off");
            DTCStrings.Add(0x0748, "Pressure Control Solenoid Electrical");
            DTCStrings.Add(0x0750, "Shift Solenoid A malfunction");
            DTCStrings.Add(0x0751, "Shift Solenoid A Performance or Stuck Off");
            DTCStrings.Add(0x0752, "Shift Solenoid A Stuck On");
            DTCStrings.Add(0x0753, "Shift Solenoid A Electrical");
            DTCStrings.Add(0x0756, "Shift Solenoid B Performance or Stuck Off");
            DTCStrings.Add(0x0757, "Shift Solenoid B Stuck On");
            DTCStrings.Add(0x0758, "Shift Solenoid B Electrical");
            DTCStrings.Add(0x0761, "Shift Solenoid C Performance or Stuck Off");
            DTCStrings.Add(0x0762, "Shift Solenoid C Stuck On");
            DTCStrings.Add(0x0763, "Shift Solenoid C Electrical");
            DTCStrings.Add(0x0768, "Shift Solenoid D Electrical");
            DTCStrings.Add(0x0773, "Shift Solenoid E Electrical");
            DTCStrings.Add(0x0790, "Normal/Performance Switch Circuit Malfunction");
            DTCStrings.Add(0x1101, "O2 Sensor Circuit Bank 1-Sensor1Voltage too Low/Air Leak");
            DTCStrings.Add(0x1102, "O2 Sensor Heating Circuit Bank 1 Sensor 1 Short to B+");
            DTCStrings.Add(0x1103, "O2 Sensor Heating Circuit Bank 1 Sensor 1 Output too Low");
            DTCStrings.Add(0x1104, "Bank 1 Sensor 2 Voltage too Low/Air Leak");
            DTCStrings.Add(0x1105, "O2 Sensor Heating Circuit Bank 1 Sensor 2 Short to B+");
            DTCStrings.Add(0x1106, "O2 Sensor Circuit Bank 2 Sensor 1 Voltage too Low/Air Leak");
            DTCStrings.Add(0x1107, "O2 Sensor Heating Circuit Bank 2 Sensor 1 Short to B+");
            DTCStrings.Add(0x1108, "O2 Sensor Heating Circuit Bank 2 Sensor 1 Output too Low");
            DTCStrings.Add(0x1109, "O2 Sensor Circuit Bank 2 Sensor 2 Voltage too Low/Air Leak");
            DTCStrings.Add(0x1110, "O2 Sensor Heating Circuit Bank 2 Sensor 2 Short to B+");
            DTCStrings.Add(0x1111, "O2 Control (Bank 1) System too lean");
            DTCStrings.Add(0x1112, "O2 Control (Bank 1) System too rich");
            DTCStrings.Add(0x1113, "Bank 1 Sensor 1 Internal Resistance too High");
            DTCStrings.Add(0x1114, "Bank 1 Sensor 2 Internal Resistance too High");
            DTCStrings.Add(0x1115, "O2 Sensor Heater Circuit Bank 1 Sensor 1 Short to Ground");
            DTCStrings.Add(0x1116, "O2 Sensor Heater Circuit Bank 1 Sensor 1 Open");
            DTCStrings.Add(0x1117, "O2 Sensor Heater Circuit Bank 1 Sensor 2 Short to Ground");
            DTCStrings.Add(0x1118, "O2 Sensor Heater Circuit Bank 1 Sensor 2 Open");
            DTCStrings.Add(0x1119, "O2 Sensor Heater Circuit Bank 2 Sensor 1 Short to Ground");
            DTCStrings.Add(0x1120, "O2 Sensor Heater Circuit Bank 2 Sensor 1 Open");
            DTCStrings.Add(0x1121, "O2 Sensor Heater Circuit Bank 2 Sensor 2 Short to Ground");
            DTCStrings.Add(0x1122, "O2 Sensor Heater Circuit Bank 2 Sensor 2 Open");
            DTCStrings.Add(0x1123, "Long Term Fuel Trim Additive Bank 1 System too Rich");
            DTCStrings.Add(0x1124, "Long Term Fuel Trim Additive Bank 1 System too Lean");
            DTCStrings.Add(0x1125, "Long Term Fuel Trim Additive Bank 2 System too Rich");
            DTCStrings.Add(0x1126, "Long Term Fuel Trim Additive Bank 2 System too Lean");
            DTCStrings.Add(0x1127, "Long Term Fuel Trim Multiplicative Bank 1 System too Rich");
            DTCStrings.Add(0x1128, "Long Term Fuel Trim Multiplicative Bank 1 System too Lean");
            DTCStrings.Add(0x1129, "Long Term Fuel Trim Multiplicative Bank 2 System too Rich");
            DTCStrings.Add(0x1130, "Long Term Fuel Trim Multiplicative Bank 2 System too Lean");
            DTCStrings.Add(0x1131, "Bank 2 Sensor 1 Internal Rsistance too High");
            DTCStrings.Add(0x1132, "O2 Sensor Heating Circuit Bank 1+2 Sensor 1 Short to B+");
            DTCStrings.Add(0x1133, "O2 Sensor Heating Circuit Bank 1+2 Sensor 1 Electrical Malfunction");
            DTCStrings.Add(0x1134, "O2 Sensor Heating Circuit Bank 1+2 Sensor 2 Short to B+");
            DTCStrings.Add(0x1135, "O2 Sensor Heating Circuit Bank 1+2 Sensor 2 Electrical Malfunction");
            DTCStrings.Add(0x1136, "Long Term Fuel Trim Additive Fuel Bank 1 System too Lean");
            DTCStrings.Add(0x1137, "Long Term Fuel Trim Additive Fuel Bank 1 System too Rich");
            DTCStrings.Add(0x1138, "Long Term Fuel Trim Additive Fuel Bank 2 System too Lean");
            DTCStrings.Add(0x1139, "Long Term Fuel Trim Additive Fuel Bank 2 System too Rich");
            DTCStrings.Add(0x1140, "Bank 2 Sensor 2 Internal Resistance too High");
            DTCStrings.Add(0x1141, "Load Calculation Cross Check Range/Performance");
            DTCStrings.Add(0x1142, "Load Calculation Cross Check Lower Limit Exceeded");
            DTCStrings.Add(0x1143, "Load Calculation Cross Check Upper Limit Exceeded");
            DTCStrings.Add(0x1144, "Mass or Volume Air Flow Circuit Open/Short to Ground");
            DTCStrings.Add(0x1145, "Mass or Volume Air Flow Circuit Short to B+");
            DTCStrings.Add(0x1146, "Mass or Volume Air Flow Circuit Supply Malfunction");
            DTCStrings.Add(0x1147, "O2 Control (Bank 2) System too lean");
            DTCStrings.Add(0x1148, "O2 Control (Bank 2) System too rich");
            DTCStrings.Add(0x1149, "O2 Control (Bank 1) Out of range");
            DTCStrings.Add(0x1150, "O2 Control (Bank 2) Out of range");
            DTCStrings.Add(0x1151, "Bank 1 Long Term Fuel Trim Range 1 Leanness Lower Limit Exceeded");
            DTCStrings.Add(0x1152, "Bank 1 Long Term Fuel Trim Range 2 Leanness Lower Limit Exceeded");
            DTCStrings.Add(0x1154, "Manifold Switch Over Malfunction");
            DTCStrings.Add(0x1155, "Manifold Absolute Pressure Sensor Circuit Short to B+");
            DTCStrings.Add(0x1156, "Manifold Absolute Pressure Sensor Circuit Open/Short to Ground");
            DTCStrings.Add(0x1157, "Manifold Absolute Pressure Sensor Circuit Power Supply Malfunction");
            DTCStrings.Add(0x1158, "Manifold Absolute Pressure Sensor Circuit Range/Performance");
            DTCStrings.Add(0x1160, "Manifold Tempurature Sensor Circuit Short to Ground");
            DTCStrings.Add(0x1161, "Manifold Tempurature Sensor Circuit Open/Short to B+");
            DTCStrings.Add(0x1162, "Fuel Tempurature Sensor Circuit Short to Ground");
            DTCStrings.Add(0x1163, "Fuel Tempurature Sensor Circuit Open/Short to B+");
            DTCStrings.Add(0x1164, "Fuel Temperature Sensor Range/Performance/Incorrect Signal");
            DTCStrings.Add(0x1165, "Bank 1 Long Term Fuel Trim Range 1 Rich Limit Exceeded");
            DTCStrings.Add(0x1166, "Bank 1 Long Term Fuel Trim Range 2 Rich Limit Exceeded");
            DTCStrings.Add(0x1171, "Throttle Actuation Potentiometer Signal 2 Range/Performance");
            DTCStrings.Add(0x1172, "Throttle Actuation Potentiometer Signal 2 Signal too Low");
            DTCStrings.Add(0x1173, "Throttle Actuation Potentiometer Signal 2 Signal too High");
            DTCStrings.Add(0x1174, "Fuel Trim Bank 1 Different injection times");
            DTCStrings.Add(0x1176, "O2 Correction Behind Catalyst Bank 1 Limit Attained");
            DTCStrings.Add(0x1177, "O2 Correction Behind Catalyst Bank 2 Limit Attained");
            DTCStrings.Add(0x1178, "Linear 02 Sensor / Pump Current Open Circuit");
            DTCStrings.Add(0x1179, "Linear 02 Sensor / Pump Current Short to ground");
            DTCStrings.Add(0x1180, "Linear 02 Sensor / Pump Current Short to B+");
            DTCStrings.Add(0x1181, "Linear 02 Sensor / Reference Voltage Open Circuit");
            DTCStrings.Add(0x1182, "Linear 02 Sensor / Reference Voltage Short to ground");
            DTCStrings.Add(0x1183, "Linear 02 Sensor / Reference Voltage Short to B+");
            DTCStrings.Add(0x1184, "Linear 02 Sensor / Common Ground Wire Open Circuit");
            DTCStrings.Add(0x1185, "Linear 02 Sensor / Common Ground Wire Short to ground");
            DTCStrings.Add(0x1186, "Linear 02 Sensor / Common Ground Wire Short to B+");
            DTCStrings.Add(0x1187, "Linear 02 Sensor / Compensation Resistor Open Circuit");
            DTCStrings.Add(0x1188, "Linear 02 Sensor / Compensation Resistor Short to ground");
            DTCStrings.Add(0x1189, "Linear 02 Sensor / Compensation Resistor Short to B+");
            DTCStrings.Add(0x1190, "Linear 02 Sensor / Reference Voltage Incorrect Signal");
            DTCStrings.Add(0x1196, "O2 Sensor Heater Circuit Bank 1 Sensor 1 Electrical Malfunction");
            DTCStrings.Add(0x1197, "O2 Sensor Heater Circuit Bank 2 Sensor 1 Electrical Malfunction");
            DTCStrings.Add(0x1198, "O2 Sensor Heater Circuit Bank 1 Sensor 2 Electrical Malfunction");
            DTCStrings.Add(0x1199, "O2 Sensor Heater Circuit Bank 2 Sensor 2 Electrical Malfunction");
            DTCStrings.Add(0x1201, "Cyl.1 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1202, "Cyl.2 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1203, "Cyl.3 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1204, "Cyl.4 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1205, "Cyl.5 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1206, "Cyl.6 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1207, "Cyl.7 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1208, "Cyl.8 Fuel Injection Circuit Electrical Malfunction");
            DTCStrings.Add(0x1209, "Intake valves for cylinder shut-off Short circuit to ground");
            DTCStrings.Add(0x1210, "Intake valves for cylinder shut-off Short to B+");
            DTCStrings.Add(0x1211, "Intake valves for cylinder shut-off Open circuit");
            DTCStrings.Add(0x1213, "Cyl.1 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1214, "Cyl.2 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1215, "Cyl.3 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1216, "Cyl.4 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1217, "Cyl.5 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1218, "Cyl.6 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1219, "Cyl.7 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1220, "Cyl.8 Fuel Injection Circuit Short to B+");
            DTCStrings.Add(0x1221, "Cylinder shut-off exhaust valves Short circuit to ground");
            DTCStrings.Add(0x1222, "Cylinder shut-off exhaust valves Short to B+");
            DTCStrings.Add(0x1223, "Cylinder shut-off exhaust valves Open circuit");
            DTCStrings.Add(0x1225, "Cyl.1 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1226, "Cyl.2 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1227, "Cyl.3 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1228, "Cyl.4 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1229, "Cyl.5 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1230, "Cyl.6 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1231, "Cyl.7 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1232, "Cyl.8 Fuel Injection Circuit Short to Ground");
            DTCStrings.Add(0x1237, "Cyl.1 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1238, "Cyl.2 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1239, "Cyl.3 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1240, "Cyl.4 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1241, "Cyl.5 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1242, "Cyl.6 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1243, "Cyl.7 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1244, "Cyl.8 Fuel Injection Circuit Open Circuit");
            DTCStrings.Add(0x1245, "Needle Lift Sensor Circuit Short to Ground");
            DTCStrings.Add(0x1246, "Needle Lift Sensor Circuit Range/Performance");
            DTCStrings.Add(0x1247, "Needle Lift Sensor Circuit Open/Short to B+");
            DTCStrings.Add(0x1248, "Injection Start Control Deviation");
            DTCStrings.Add(0x1249, "Fuel consumption signal Electrical Fault in Circuit");
            DTCStrings.Add(0x1250, "Fuel Level Too Low");
            DTCStrings.Add(0x1251, "Start of Injection Solenoid Circuit Short to B+");
            DTCStrings.Add(0x1252, "Start of Injection Solenoid Circuit Open/Short to Ground");
            DTCStrings.Add(0x1253, "Fuel consumption signal Short to ground");
            DTCStrings.Add(0x1254, "Fuel consumption signal Short to B+");
            DTCStrings.Add(0x1255, "Engine Coolant Tempurature Circuit Short to Ground");
            DTCStrings.Add(0x1256, "Engine Coolant Tempurature Circuit Open/Short to B+");
            DTCStrings.Add(0x1257, "Engine Coolant System Valve Open");
            DTCStrings.Add(0x1258, "Engine Coolant System Valve Short to B+");
            DTCStrings.Add(0x1259, "Engine Coolant System Valve Short to Ground");
            DTCStrings.Add(0x1280, "Fuel Injection Air Control Valve Circuit Flow too Low");
            DTCStrings.Add(0x1283, "Fuel Injection Air Control Valve Circuit Electrical Malfunction");
            DTCStrings.Add(0x1284, "Fuel Injection Air Control Valve Circuit Open");
            DTCStrings.Add(0x1285, "Fuel Injection Air Control Valve Circuit Short to Ground");
            DTCStrings.Add(0x1286, "Fuel Injection Air Control Valve Circuit Short to B+");
            DTCStrings.Add(0x1287, "Turbocharger bypass valve open");
            DTCStrings.Add(0x1288, "Turbocharger bypass valve short to B+");
            DTCStrings.Add(0x1289, "Turbocharger bypass valve short to ground");
            DTCStrings.Add(0x1296, "Cooling system malfunction");
            DTCStrings.Add(0x1297, "Connection turbocharger - throttle valve pressure hose");
            DTCStrings.Add(0x1300, "Misfire detected Reason: Fuel level too low");
            DTCStrings.Add(0x1319, "Knock Sensor 1 Circuit Short to Ground");
            DTCStrings.Add(0x1320, "Knock Sensor 2 Circuit Short to Ground");
            DTCStrings.Add(0x1321, "Knock Sensor 3 Circuit Low Input");
            DTCStrings.Add(0x1322, "Knock Sensor 3 Circuit High Input");
            DTCStrings.Add(0x1323, "Knock Sensor 4 Circuit Low Input");
            DTCStrings.Add(0x1324, "Knock Sensor 4 Circuit High Input");
            DTCStrings.Add(0x1325, "Cyl.1 Knock Control Limit Attained");
            DTCStrings.Add(0x1326, "Cyl.2 Knock Control Limit Attained");
            DTCStrings.Add(0x1327, "Cyl.3 Knock Control Limit Attained");
            DTCStrings.Add(0x1328, "Cyl.4 Knock Control Limit Attained");
            DTCStrings.Add(0x1329, "Cyl.5 Knock Control Limit Attained");
            DTCStrings.Add(0x1330, "Cyl.6 Knock Control Limit Attained");
            DTCStrings.Add(0x1331, "Cyl.7 Knock Control Limit Attained");
            DTCStrings.Add(0x1332, "Cyl.8 Knock Control Limit Attained");
            DTCStrings.Add(0x1335, "Engine Torque Monitoring 2 Control Limit Exceeded");
            DTCStrings.Add(0x1336, "Engine Torque Monitoring Adaptation at limit");
            DTCStrings.Add(0x1337, "Camshaft Position Sensor Bank 1 Short to Ground");
            DTCStrings.Add(0x1338, "Camshaft Position Sensor Bank 1 Open Circuit/Short to B+");
            DTCStrings.Add(0x1339, "Crankshaft Position /Engine Speed Sensor Cross Connected");
            DTCStrings.Add(0x1340, "Crankshaft/Camshaft Position Sensor Signals Out of Sequence");
            DTCStrings.Add(0x1341, "Ignition Coil Power Output Stage 1 Short to Ground");
            DTCStrings.Add(0x1342, "Ignition Coil Power Output Stage 1 Short to B+");
            DTCStrings.Add(0x1343, "Ignition Coil Power Output Stage 2 Short to Ground");
            DTCStrings.Add(0x1344, "Ignition Coil Power Output Stage 2 Short to B+");
            DTCStrings.Add(0x1345, "Ignition Coil Power Output Stage 3 Short to Ground");
            DTCStrings.Add(0x1346, "Ignition Coil Power Output Stage 3 Short to B+");
            DTCStrings.Add(0x1347, "Bank 2 Crankshaft/Camshaft Position Sensor Signal Out of Sequence");
            DTCStrings.Add(0x1348, "Ignition Coil Power Output Stage 1 Open Circuit");
            DTCStrings.Add(0x1349, "Ignition Coil Power Output Stage 2 Open Circuit");
            DTCStrings.Add(0x1350, "Ignition Coil Power Output Stage 3 Open Circuit");
            DTCStrings.Add(0x1354, "Modulation Piston Displacement Sensor Circuit Malfunction");
            DTCStrings.Add(0x1355, "Cyl. 1 ignition circuit Open Circuit");
            DTCStrings.Add(0x1356, "Cyl. 1 ignition circuit Short to B+");
            DTCStrings.Add(0x1357, "Cyl. 1 ignition circuit Short to ground");
            DTCStrings.Add(0x1358, "Cyl. 2 ignition circuit Open Circuit");
            DTCStrings.Add(0x1359, "Cyl. 2 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1360, "Cyl. 2 ignition circuit Short Circuit to Ground");
            DTCStrings.Add(0x1361, "Cyl. 3 ignition circuit Open Circuit");
            DTCStrings.Add(0x1362, "Cyl. 3 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1363, "Cyl. 3 ignition circuit Short Circuit to ground");
            DTCStrings.Add(0x1364, "Cyl. 4 ignition circuit Open Circuit");
            DTCStrings.Add(0x1365, "Cyl. 4 ignition circuit Short circuit to B+");
            DTCStrings.Add(0x1366, "Cyl. 4 ignition circuit Short circuit to ground");
            DTCStrings.Add(0x1367, "Cyl. 5 ignition circuit Open Circuit");
            DTCStrings.Add(0x1368, "Cyl. 5 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1369, "Cyl. 5 ignition circuit short to ground");
            DTCStrings.Add(0x1370, "Cyl. 6 ignition circuit Open Circuit");
            DTCStrings.Add(0x1371, "Cyl. 6 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1372, "Cyl. 6 ignition circuit short to ground");
            DTCStrings.Add(0x1373, "Cyl. 7 ignition circuit Open Circuit");
            DTCStrings.Add(0x1374, "Cyl. 7 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1375, "Cyl. 7 ignition circuit short to ground");
            DTCStrings.Add(0x1376, "Cyl. 8 ignition circuit Open Circuit");
            DTCStrings.Add(0x1377, "Cyl. 8 ignition circuit Short Circuit to B+");
            DTCStrings.Add(0x1378, "Cyl. 8 ignition circuit short to ground");
            DTCStrings.Add(0x1386, "Internal Control Module Knock Control CircuitError");
            DTCStrings.Add(0x1387, "Internal Control Module altitude sensor error");
            DTCStrings.Add(0x1388, "Internal Control Module drive by wire error");
            DTCStrings.Add(0x1391, "Camshaft Position Sensor Bank 2 Short to Ground");
            DTCStrings.Add(0x1392, "Camshaft Position Sensor Bank 2 Open Circuit/Short to B+");
            DTCStrings.Add(0x1393, "Ignition Coil Power Output Stage 1 Electrical Malfunction");
            DTCStrings.Add(0x1394, "Ignition Coil Power Output Stage 2 Electrical Malfunction");
            DTCStrings.Add(0x1395, "Ignition Coil Power Output Stage 3 Electrical Malfunction");
            DTCStrings.Add(0x1396, "Engine Speed Sensor Missing Tooth");
            DTCStrings.Add(0x1397, "Engine speed wheel Adaptation limit reached");
            DTCStrings.Add(0x1398, "Engine RPM signal TD Short to ground");
            DTCStrings.Add(0x1399, "Engine RPM signal TD Short Circuit to B+");
            DTCStrings.Add(0x1400, "EGR Valve Circuit Electrical Malfunction");
            DTCStrings.Add(0x1401, "EGR Valve Circuit Short to Ground");
            DTCStrings.Add(0x1402, "EGR Valve Circuit Short to B+");
            DTCStrings.Add(0x1403, "EGR Flow Deviation");
            DTCStrings.Add(0x1404, "EGR Flow Basic Setting not carried out");
            DTCStrings.Add(0x1406, "EGR Tempurature Sensor Range/Performance");
            DTCStrings.Add(0x1407, "EGR Tempurature Sensor Signal too Low");
            DTCStrings.Add(0x1408, "EGR Tempurature Sensor Signal too High");
            DTCStrings.Add(0x1409, "Tank Ventilation Valve Circuit Electrical Malfunction");
            DTCStrings.Add(0x1410, "Tank Ventilation Valve Circuit Short to B+");
            DTCStrings.Add(0x1411, "Secondary Air Injection System Bank 2 Flow too Flow");
            DTCStrings.Add(0x1412, "EGR Differential Pressure Sensor Signal too Low");
            DTCStrings.Add(0x1413, "EGR Differential Pressure Sensor Signal too High");
            DTCStrings.Add(0x1414, "Secondary Air Injection System Bank 2 Leak Detected");
            DTCStrings.Add(0x1417, "Fuel Level Sensor Circuit Signal too Low");
            DTCStrings.Add(0x1418, "Fuel Level Sensor Circuit Signal too High");
            DTCStrings.Add(0x1420, "Secondary Air Injection Valve Circuit Electrical Malfunction");
            DTCStrings.Add(0x1421, "Secondary Air Injection Valve Circuit Short to Ground");
            DTCStrings.Add(0x1422, "Secondary Air Injection System Control Valve Circuit Short to B+");
            DTCStrings.Add(0x1423, "Secondary Air Injection System Bank 1 Flow too Low");
            DTCStrings.Add(0x1424, "Secondary Air Injection System Bank 1 Leak Detected");
            DTCStrings.Add(0x1425, "Tank Ventilation Valve Short to Ground");
            DTCStrings.Add(0x1426, "Tank Ventilation Valve Open");
            DTCStrings.Add(0x1432, "Secondary Air Injection Valve Open");
            DTCStrings.Add(0x1433, "Secondary Air Injection System Pump Relay Circuit open");
            DTCStrings.Add(0x1434, "Secondary Air Injection System Pump Relay Circuit Short to B+");
            DTCStrings.Add(0x1435, "Secondary Air Injection System Pump Relay Circuit Short to ground");
            DTCStrings.Add(0x1436, "Secondary Air Injection System Pump Relay Circuit Electrical Malfunction");
            DTCStrings.Add(0x1439, "EGR Potentiometer Error in Basic Seting");
            DTCStrings.Add(0x1440, "EGR Valve Power Stage Open");
            DTCStrings.Add(0x1441, "EGR Valve Circuit Open/Short to Ground");
            DTCStrings.Add(0x1442, "EGR Valve Position Sensor Signal too high");
            DTCStrings.Add(0x1443, "EGR Valve Position Sensor Signal too low");
            DTCStrings.Add(0x1444, "EGR Valve Position Sensor range/performance");
            DTCStrings.Add(0x1445, "Catalyst Tempurature Sensor 2 Circuit Range/Performance");
            DTCStrings.Add(0x1446, "Catalyst Tempurature Circuit Short to Ground");
            DTCStrings.Add(0x1447, "Catalyst Tempurature Circuit Open/Short to B+");
            DTCStrings.Add(0x1448, "Catalyst Tempurature Sensor 2 Circuit Short to Ground");
            DTCStrings.Add(0x1449, "Catalyst Tempurature Sensor 2 Circuit Open/Short to B+");
            DTCStrings.Add(0x1450, "Secondary Air Injection System Circuit Short to B+");
            DTCStrings.Add(0x1451, "Secondary Air Injection System Circuit Short to Ground");
            DTCStrings.Add(0x1452, "Secondary Air Injection System Open Circuit");
            DTCStrings.Add(0x1453, "Exhaust gas temperature sensor 1 open/short to B+");
            DTCStrings.Add(0x1454, "Exhaust gas temperature sensor short 1 to ground");
            DTCStrings.Add(0x1455, "Exhaust gas temperature sensor 1 range/performance");
            DTCStrings.Add(0x1456, "Exhaust gas temperature control bank 1 limit attained");
            DTCStrings.Add(0x1457, "Exhaust gas temperature sensor 2 open/short to B+");
            DTCStrings.Add(0x1458, "Exhaust gas temperature sensor 2 short to ground");
            DTCStrings.Add(0x1459, "Exhaust gas temperature sensor 2 range/performance");
            DTCStrings.Add(0x1460, "Exhaust gas temperature control bank 2 limit attained");
            DTCStrings.Add(0x1461, "Exhaust gas temperature control bank 1 Range/Performance");
            DTCStrings.Add(0x1462, "Exhaust gas temperature control bank 2 Range/Performance");
            DTCStrings.Add(0x1465, "Additive Pump Short Circuit to B+");
            DTCStrings.Add(0x1466, "Additive Pump Open/Short to Ground");
            DTCStrings.Add(0x1467, "EVAP Canister Purge Solenoid Valve Short Circuit to B+");
            DTCStrings.Add(0x1468, "EVAP Canister Purge Solenoid Valve Short Circuit to Ground");
            DTCStrings.Add(0x1469, "EVAP Canister Purge Solenoid Valve Open Circuit");
            DTCStrings.Add(0x1470, "EVAP Emission Control LDP Circuit Electrical Malfunction");
            DTCStrings.Add(0x1471, "EVAP Emission Control LDP Circuit Short to B+");
            DTCStrings.Add(0x1472, "EVAP Emission Control LDP Circuit Short to Ground");
            DTCStrings.Add(0x1473, "EVAP Emission Control LDP Circuit Open Circuit");
            DTCStrings.Add(0x1474, "EVAP Canister Purge Solenoid Valve electrical malfunction");
            DTCStrings.Add(0x1475, "EVAP Emission Control LDP Circuit Malfunction/Signal CircuitOpen");
            DTCStrings.Add(0x1476, "EVAP Emission Control LDP Circuit Malfunction/Insufficient Vacuum");
            DTCStrings.Add(0x1477, "EVAP Emission Control LDP Circuit Malfunction");
            DTCStrings.Add(0x1478, "EVAP Emission Control LDP Circuit Clamped Tube Detected");
            DTCStrings.Add(0x1479, "Vacuum system, brakes - mechanical fault");
            DTCStrings.Add(0x1500, "Fuel Pump Relay Circuit Electrical Malfunction");
            DTCStrings.Add(0x1501, "Fuel Pump Relay Circuit Short to Ground");
            DTCStrings.Add(0x1502, "Fuel Pump Relay Circuit Short to B+");
            DTCStrings.Add(0x1503, "Load signal from Alternator Terminal DF Range/performance/Incorrect Signal");
            DTCStrings.Add(0x1504, "Intake Air System Bypass Leak Detected");
            DTCStrings.Add(0x1505, "Closed Throttle Position Does Not Close/Open Circuit");
            DTCStrings.Add(0x1506, "Closed Throttle Position Switch Does Not Open/Short to Ground");
            DTCStrings.Add(0x1507, "Idle System Learned Value Lower Limit Attained");
            DTCStrings.Add(0x1508, "Idle System Learned Value Upper Limit Attained");
            DTCStrings.Add(0x1509, "Idle Air Control Circuit Electrical Malfunction");
            DTCStrings.Add(0x1510, "Idle Air Control Circuit Short to B+");
            DTCStrings.Add(0x1511, "Intake Manifold Changeover Valve circuit electrical malfunction");
            DTCStrings.Add(0x1512, "Intake Manifold Changeover Valve circuit Short to B+");
            DTCStrings.Add(0x1513, "Intake Manifold Changeover Valve2 circuit Short to B+");
            DTCStrings.Add(0x1514, "Intake Manifold Changeover Valve2 circuit Short to ground");
            DTCStrings.Add(0x1515, "Intake Manifold Changeover Valve circuit Short to Ground");
            DTCStrings.Add(0x1516, "Intake Manifold Changeover Valve circuit Open");
            DTCStrings.Add(0x1517, "Main Relay Circuit Electrical Malfunction");
            DTCStrings.Add(0x1518, "Main Relay Circuit Short to B+");
            DTCStrings.Add(0x1519, "Intake Camshaft Control Bank 1 Malfunction");
            DTCStrings.Add(0x1520, "Intake Manifold Changeover Valve 2 circuit Open");
            DTCStrings.Add(0x1521, "Intake Manifold Changeover Valve 2 circuit electrical malfunction");
            DTCStrings.Add(0x1522, "Intake Camshaft Control Bank 2 Malfunction");
            DTCStrings.Add(0x1523, "Crash Signal from Airbag Control Unit range/performance");
            DTCStrings.Add(0x1525, "Intake Camshaft Control Circuit Bank 1 Electrical Malfunction");
            DTCStrings.Add(0x1526, "Intake Camshaft Control Circuit Bank 1 Short to B+");
            DTCStrings.Add(0x1527, "Intake Camshaft Control Circuit Bank 1 Short to Ground");
            DTCStrings.Add(0x1528, "Intake Camshaft Control Circuit Bank 1 Open");
            DTCStrings.Add(0x1529, "Camshaft Control Circuit Short to B+");
            DTCStrings.Add(0x1530, "Camshaft Control Circuit Short to ground");
            DTCStrings.Add(0x1531, "Camshaft Control Circuit open");
            DTCStrings.Add(0x1533, "Intake Camshaft Control Circuit Bank 2 Electrical Malfunction");
            DTCStrings.Add(0x1534, "Intake Camshaft Control Circuit Bank 2 Short to B+");
            DTCStrings.Add(0x1535, "Intake Camshaft Control Circuit Bank 2 Short to Ground");
            DTCStrings.Add(0x1536, "Intake Camshaft Control Circuit Bank 2 Open");
            DTCStrings.Add(0x1537, "Engine Shutoff Solenoid Malfunction");
            DTCStrings.Add(0x1538, "Engine Shutoff Solenoid Open/Short to Ground");
            DTCStrings.Add(0x1539, "Clutch Vacuum Vent Valve Switch Incorrect signal");
            DTCStrings.Add(0x1540, "Vehicle Speed Sensor High Input");
            DTCStrings.Add(0x1541, "Fuel Pump Relay Circuit Open");
            DTCStrings.Add(0x1542, "Throttle Actuation Potentiometer Range/Performance");
            DTCStrings.Add(0x1543, "Throttle Actuation Potentiometer Signal too Low");
            DTCStrings.Add(0x1544, "Throttle Actuation Potentiometer Signal too High");
            DTCStrings.Add(0x1545, "Throttle Position Contr Malfunction");
            DTCStrings.Add(0x1546, "Boost Pressure Control Valve Short to B+");
            DTCStrings.Add(0x1547, "Boost Pressure Control Valve Short to Ground");
            DTCStrings.Add(0x1548, "Boost Pressure Control Valve Open");
            DTCStrings.Add(0x1549, "Boost Pressure Control Valve Short to Ground");
            DTCStrings.Add(0x1550, "Charge Pressure Deviation");
            DTCStrings.Add(0x1551, "Barometric Pressure Sensor Circuit Short to B+");
            DTCStrings.Add(0x1552, "Barometric Pressure Sensor Circuit Open/Short to Ground");
            DTCStrings.Add(0x1553, "Barometric/manifold pressure signal ratio out of range");
            DTCStrings.Add(0x1554, "Idle Speed ControlThrottle Position Basic Setting Conditions not met");
            DTCStrings.Add(0x1555, "Charge Pressure Upper Limit exceeded");
            DTCStrings.Add(0x1556, "Charge Pressure Control Negative Deviation");
            DTCStrings.Add(0x1557, "Charge Pressure Control Positive Deviation");
            DTCStrings.Add(0x1558, "Throttle Actuator Electrical Malfunction");
            DTCStrings.Add(0x1559, "Idle Speed ControlThrottle Position Adaptation Malfunction");
            DTCStrings.Add(0x1560, "Maximum Engine Speed Exceeded");
            DTCStrings.Add(0x1561, "Quantity Adjuster Deviation");
            DTCStrings.Add(0x1562, "Quantity Adjuster Upper Limit Attained");
            DTCStrings.Add(0x1563, "Quantity Adjuster Lower Limit Attained");
            DTCStrings.Add(0x1564, "Idle Speed ControlThrottle Position Low Voltage During Adaptation");
            DTCStrings.Add(0x1565, "Idle Speed Control Throttle Position lower limit not attained");
            DTCStrings.Add(0x1566, "Load signal from A/C compressor range/performance");
            DTCStrings.Add(0x1567, "Load signal from A/C compressor no signal");
            DTCStrings.Add(0x1568, "Idle Speed ControlThrottle Position mechanical Malfunction");
            DTCStrings.Add(0x1569, "Cruise control switch Incorrect signal");
            DTCStrings.Add(0x1570, "Control Module Locked");
            DTCStrings.Add(0x1571, "Left Engine Mount Solenoid Valve Short to B+");
            DTCStrings.Add(0x1572, "Left Engine Mount Solenoid Valve Short to ground");
            DTCStrings.Add(0x1573, "Left Engine Mount Solenoid Valve Open circuit");
            DTCStrings.Add(0x1574, "Left Engine Mount Solenoid Valve Electrical fault in circuit");
            DTCStrings.Add(0x1575, "Right Engine Mount Solenoid Valve Short to B+");
            DTCStrings.Add(0x1576, "Right Engine Mount Solenoid Valve Short to ground");
            DTCStrings.Add(0x1577, "Right Engine Mount Solenoid Valve Open circuit");
            DTCStrings.Add(0x1578, "Right Engine Mount Solenoid Valve Electrical fault in circuit");
            DTCStrings.Add(0x1579, "Idle Speed ControlThrottle Position Adaptation not started");
            DTCStrings.Add(0x1580, "Throttle Actuator B1 Malfunction");
            DTCStrings.Add(0x1581, "Idle Speed ControlThrottle Position Basic Setting Not Carried Out");
            DTCStrings.Add(0x1582, "Idle Adaptation at Limit");
            DTCStrings.Add(0x1583, "Transmission mount valves Short to B+");
            DTCStrings.Add(0x1584, "Transmission mount valves Short to ground");
            DTCStrings.Add(0x1585, "Transmission mount valves Open circuit");
            DTCStrings.Add(0x1586, "Engine mount solenoid valves Short to B+");
            DTCStrings.Add(0x1587, "Engine mount solenoid valves Short to ground");
            DTCStrings.Add(0x1588, "Engine mount solenoid valves Open circuit");
            DTCStrings.Add(0x1600, "Power Supply (B+) Terminal 15 Low Voltage");
            DTCStrings.Add(0x1602, "Power Supply (B+) Terminal 30 Low Voltage");
            DTCStrings.Add(0x1603, "Internal Control Module Malfunction");
            DTCStrings.Add(0x1604, "Internal Control Module Driver Error");
            DTCStrings.Add(0x1605, "Rough Road/Acceleration Sensor Electrical Malfunction");
            DTCStrings.Add(0x1606, "Rough Road Spec Engine Torque ABS-ECU Electrical Malfunction");
            DTCStrings.Add(0x1607, "Vehicle speed signal Error message from instrument cluster");
            DTCStrings.Add(0x1608, "Steering angle signal Error message from steering angle sensor");
            DTCStrings.Add(0x1609, "Crash shut-down activated");
            DTCStrings.Add(0x1611, "MIL Call-up Circuit/Transmission Control Module Short to Ground");
            DTCStrings.Add(0x1612, "Electronic Control Module Incorrect Coding");
            DTCStrings.Add(0x1613, "MIL Call-up Circuit Open/Short to B+");
            DTCStrings.Add(0x1614, "MIL Call-up Circuit/Transmission Control Module Range/Performance");
            DTCStrings.Add(0x1615, "Engine Oil Temperature Sensor Circuit range/performance");
            DTCStrings.Add(0x1616, "Glow Plug/Heater Indicator Circuit Short to B+");
            DTCStrings.Add(0x1617, "Glow Plug/Heater Indicator Circuit Open/Short to Ground");
            DTCStrings.Add(0x1618, "Glow Plug/Heater Relay Circuit Short to B+");
            DTCStrings.Add(0x1619, "Glow Plug/Heater Relay Circuit Open/Short to Ground");
            DTCStrings.Add(0x1620, "Engine coolant temperature signal open/short to B+");
            DTCStrings.Add(0x1621, "Engine coolant temperature signal short to ground");
            DTCStrings.Add(0x1622, "Engine coolant temperature signal range/performance");
            DTCStrings.Add(0x1623, "Data Bus Powertrain No Communication");
            DTCStrings.Add(0x1624, "MIL Request Signal active");
            DTCStrings.Add(0x1625, "Data-Bus Powertrain Unplausible Message from Transmission Control");
            DTCStrings.Add(0x1626, "Data-Bus Powertrain Missing Message from Transmission Control");
            DTCStrings.Add(0x1627, "Data-Bus Powertrain missing message from fuel injection pump");
            DTCStrings.Add(0x1628, "Data-Bus Powertrain missing message from steering sensor");
            DTCStrings.Add(0x1629, "Data-Bus Powertrain missing message from distance control");
            DTCStrings.Add(0x1630, "Accelerator Pedal Position Sensor 1 Signal too Low");
            DTCStrings.Add(0x1631, "Accelerator Pedal Position Sensor 1 Signal too High");
            DTCStrings.Add(0x1632, "Accelerator Pedal Position Sensor 1 Power Supply Malfunction");
            DTCStrings.Add(0x1633, "Accelerator Pedal Position Sensor 2 Signal too Low");
            DTCStrings.Add(0x1634, "Accelerator Pedal Position Sensor 2 Signal too High");
            DTCStrings.Add(0x1635, "Data Bus Powertrain missing message f.air condition control");
            DTCStrings.Add(0x1636, "Data Bus Powertrain missing message from Airbag control");
            DTCStrings.Add(0x1637, "Data Bus Powertrain missing message f.central electr.control");
            DTCStrings.Add(0x1638, "Data Bus Powertrain missing message from clutch control");
            DTCStrings.Add(0x1639, "Accelerator Pedal Position Sensor 1+2 Range/Performance");
            DTCStrings.Add(0x1640, "Internal Control Module (EEPROM) Error");
            DTCStrings.Add(0x1641, "Please check DTC Memory of Air Condition ECU");
            DTCStrings.Add(0x1642, "Please check DTC Memory of Airbag ECU");
            DTCStrings.Add(0x1643, "Please check DTC Memory of central electric ECU");
            DTCStrings.Add(0x1644, "Please check DTC Memory of clutch ECU");
            DTCStrings.Add(0x1645, "Data Bus Powertrain missing message from all wheel drive control");
            DTCStrings.Add(0x1646, "Please Check DTC Memory of all wheel drive ECU");
            DTCStrings.Add(0x1647, "Please check coding of ECUs in Data Bus Powertrain");
            DTCStrings.Add(0x1648, "Data Bus Powertrain Malfunction");
            DTCStrings.Add(0x1649, "Data Bus Powertrain Missing message from ABS Control Module");
            DTCStrings.Add(0x1650, "Data Bus Powertrain Missing message from instrument panel ECU");
            DTCStrings.Add(0x1651, "Data Bus Powertrain missing messages");
            DTCStrings.Add(0x1652, "Please check DTC Memory of transmission ECU");
            DTCStrings.Add(0x1653, "Please check DTC Memory of ABS Control Module");
            DTCStrings.Add(0x1654, "Please check DTC Memory of control panel ECU");
            DTCStrings.Add(0x1655, "Please check DTC Memory of ADR Control Module");
            DTCStrings.Add(0x1656, "A/C clutch relay circuit short to ground");
            DTCStrings.Add(0x1657, "A/C clutch relay circuit short to B+");
            DTCStrings.Add(0x1658, "Data Bus Powertrain Incorrect signal from ADR Control Module");
            DTCStrings.Add(0x1676, "Drive by Wire-MIL Circuit Electrical Malfunction");
            DTCStrings.Add(0x1677, "Drive by Wire-MIL Circuit Short to B+");
            DTCStrings.Add(0x1678, "Drive by Wire-MIL Circuit Short to Ground");
            DTCStrings.Add(0x1679, "Drive by Wire-MIL Circuit Open");
            DTCStrings.Add(0x1681, "Control Unit Programming, Programming not Finished");
            DTCStrings.Add(0x1683, "CAN data bus, SRS - implausible signal");
            DTCStrings.Add(0x1684, "Control Unit Programming, Communication Error");
            DTCStrings.Add(0x1686, "Control Unit Error, Programming Error");
            DTCStrings.Add(0x1690, "Malfunction Indication Light Malfunction");
            DTCStrings.Add(0x1691, "Malfunction Indication Light Open");
            DTCStrings.Add(0x1692, "Malfunction Indication Light Short to Ground");
            DTCStrings.Add(0x1693, "Malfunction Indication Light Short to B+");
            DTCStrings.Add(0x1694, "Malfunction Indication Light Open/Short to Ground");
            DTCStrings.Add(0x1696, "CAN data bus, steering column electronics - incorrect signal");
            DTCStrings.Add(0x1704, "Kick Down Switch Malfunction");
            DTCStrings.Add(0x1705, "Gear/Ratio Monitoring Adaptation limit reached");
            DTCStrings.Add(0x1711, "Wheel Speed Signal 1 Range/Performance");
            DTCStrings.Add(0x1716, "Wheel Speed Signal 2 Range/Performance");
            DTCStrings.Add(0x1721, "Wheel Speed Signal 3 Range/Performance");
            DTCStrings.Add(0x1723, "Starter Interlock Circuit Open");
            DTCStrings.Add(0x1724, "Starter Interlock Circuit Short to Ground");
            DTCStrings.Add(0x1726, "Wheel Speed Signal 4 Range/Performance");
            DTCStrings.Add(0x1728, "Different Wheel Speed Signals Range/Performance");
            DTCStrings.Add(0x1729, "Starter Interlock Circuit Short to B+");
            DTCStrings.Add(0x1733, "Tiptronic Switch Down Circuit Short to Ground");
            DTCStrings.Add(0x1739, "Tiptronic Switch up Circuit Short to Ground");
            DTCStrings.Add(0x1740, "Clutch temperature control");
            DTCStrings.Add(0x1741, "Clutch pressure adaptation at limit");
            DTCStrings.Add(0x1742, "Clutch torque adaptation at limit");
            DTCStrings.Add(0x1743, "Clutch slip control signal too high");
            DTCStrings.Add(0x1744, "Tiptronic Switch Recognition Circuit Short to Ground");
            DTCStrings.Add(0x1745, "Transmission Control Unit Relay Short to B+");
            DTCStrings.Add(0x1746, "Transmission Control Unit Relay Malfunction");
            DTCStrings.Add(0x1747, "Transmission Control Unit Relay Open/Short to Ground");
            DTCStrings.Add(0x1748, "Transmission Control Unit Self-Check");
            DTCStrings.Add(0x1749, "Transmission Control Unit Incorrect Coded");
            DTCStrings.Add(0x1750, "Power Supply Voltage Low Voltage");
            DTCStrings.Add(0x1751, "Power Supply Voltage High Voltage");
            DTCStrings.Add(0x1752, "Power Supply Malfunction");
            DTCStrings.Add(0x1760, "Shift Lock Malfunction");
            DTCStrings.Add(0x1761, "Shift Lock Short to Ground");
            DTCStrings.Add(0x1762, "Shift Lock Short to B+");
            DTCStrings.Add(0x1763, "Shift Lock Open");
            DTCStrings.Add(0x1764, "Transmission temperature control");
            DTCStrings.Add(0x1765, "Hydraulic Pressure Sensor 2 adaptation at limit");
            DTCStrings.Add(0x1766, "Throttle Angle Signal Stuck Off");
            DTCStrings.Add(0x1767, "Throttle Angle Signal Stuck On");
            DTCStrings.Add(0x1768, "Hydraulic Pressure Sensor 2 Too High");
            DTCStrings.Add(0x1769, "Hydraulic Pressure Sensor 2 Too Low");
            DTCStrings.Add(0x1770, "Load Signal Range/Performance");
            DTCStrings.Add(0x1771, "Load Signal Stuck Off");
            DTCStrings.Add(0x1772, "Load Signal Stuck On");
            DTCStrings.Add(0x1773, "Hydraulic Pressure Sensor 1 Too High");
            DTCStrings.Add(0x1774, "Hydraulic Pressure Sensor 1 Too Low");
            DTCStrings.Add(0x1775, "Hydraulic Pressure Sensor 1 adaptation at limit");
            DTCStrings.Add(0x1776, "Hydraulic Pressure Sensor 1 range/performance");
            DTCStrings.Add(0x1777, "Hydraulic Pressure Sensor 2 range/performance");
            DTCStrings.Add(0x1778, "Solenoid EV7 Electrical Malfunction");
            DTCStrings.Add(0x1781, "Engine Torque Reduction Open/Short to Ground");
            DTCStrings.Add(0x1782, "Engine Torque Reduction Short to B+");
            DTCStrings.Add(0x1784, "Shift up/down Wire Open/Short to Ground");
            DTCStrings.Add(0x1785, "Shift up/down Wire Short to B+");
            DTCStrings.Add(0x1786, "Reversing Light Circuit Open");
            DTCStrings.Add(0x1787, "Reversing Light Circuit Short to Ground");
            DTCStrings.Add(0x1788, "Reversing Light Circuit Short to B+");
            DTCStrings.Add(0x1789, "Idle Speed Intervention Circuit Error Message from Engine Control");
            DTCStrings.Add(0x1790, "Transmission Range Display Circuit Open");
            DTCStrings.Add(0x1791, "Transmission Range Display Circuit Short to Ground");
            DTCStrings.Add(0x1792, "Transmission Range Display Circuit Short to B+");
            DTCStrings.Add(0x1793, "Output Speed Sensor 2 Circuit No Signal");
            DTCStrings.Add(0x1795, "Vehicle Speed Signal Circuit Open");
            DTCStrings.Add(0x1796, "Vehicle Speed Signal Circuit Short to Ground");
            DTCStrings.Add(0x1797, "Vehicle Speed Signal Circuit Short to B+");
            DTCStrings.Add(0x1798, "Output Speed Sensor 2 Circuit Range/Performance");
            DTCStrings.Add(0x1799, "Output Speed Sensor 2 Circuit Rpm too High");
            DTCStrings.Add(0x1813, "Pressure Control Solenoid 1 Electrical");
            DTCStrings.Add(0x1814, "Pressure Control Solenoid 1 Open/Short to Ground");
            DTCStrings.Add(0x1815, "Pressure Control Solenoid 1 Short to B+");
            DTCStrings.Add(0x1818, "Pressure Control Solenoid 2 Electrical");
            DTCStrings.Add(0x1819, "Pressure Control Solenoid 2 Open/Short to Ground");
            DTCStrings.Add(0x1820, "Pressure Control Solenoid 2 Short to B+");
            DTCStrings.Add(0x1823, "Pressure Control Solenoid 3 Electrical");
            DTCStrings.Add(0x1824, "Pressure Control Solenoid 3 Open/Short to Ground");
            DTCStrings.Add(0x1825, "Pressure Control Solenoid 3 Short to B+");
            DTCStrings.Add(0x1828, "Pressure Control Solenoid 4 Electrical");
            DTCStrings.Add(0x1829, "Pressure Control Solenoid 4 Open/Short to Ground");
            DTCStrings.Add(0x1830, "Pressure Control Solenoid 4 Short to B+");
            DTCStrings.Add(0x1834, "Pressure Control Solenoid 5 Open/Short to Ground");
            DTCStrings.Add(0x1835, "Pressure Control Solenoid 5 Short to B+");
            DTCStrings.Add(0x1841, "Engine/Transmission Control Modules Versions do not match");
            DTCStrings.Add(0x1842, "Please check DTC Memory of instrument panel ECU");
            DTCStrings.Add(0x1843, "Please check DTC Memory of ADR Control Module");
            DTCStrings.Add(0x1844, "Please check DTC Memory of central electric control ECU");
            DTCStrings.Add(0x1847, "Please check DTC Memory of brake system ECU");
            DTCStrings.Add(0x1848, "Please check DTC Memory of engine ECU");
            DTCStrings.Add(0x1849, "Please check DTC Memory of transmission ECU");
            DTCStrings.Add(0x1850, "Data-Bus Powertrain Missing Message from Engine Control");
            DTCStrings.Add(0x1851, "Data-Bus Powertrain Missing Message from Brake Control");
            DTCStrings.Add(0x1852, "Data-Bus Powertrain Unplausible Message from Engine Control");
            DTCStrings.Add(0x1853, "Data-Bus Powertrain Unplausible Message from Brake Control");
            DTCStrings.Add(0x1854, "Data-Bus Powertrain Hardware Defective");
            DTCStrings.Add(0x1855, "Data-Bus Powertrain Software version Control");
            DTCStrings.Add(0x1856, "Throttle/Pedal Position Sensor A Circuit Error Message from Engine Control");
            DTCStrings.Add(0x1857, "Load Signal Error Message from Engine Control");
            DTCStrings.Add(0x1858, "Engine Speed Input Circuit Error Message from Engine Control");
            DTCStrings.Add(0x1859, "Brake Switch Circuit Error Message from Engine Control");
            DTCStrings.Add(0x1860, "Kick Down Switch Error Message from Engine Control");
            DTCStrings.Add(0x1861, "Throttle Position (TP) sensor Error Message from ECM");
            DTCStrings.Add(0x1862, "Data Bus Powertrain Missing message from instrument panel ECU");
            DTCStrings.Add(0x1863, "Data Bus Powertrain Missing Message from Steerin Angle Sensor");
            DTCStrings.Add(0x1864, "Data Bus Powertrain Missing message from ADR control module");
            DTCStrings.Add(0x1865, "Data Bus Powertrain Missing message from central electronics");
            DTCStrings.Add(0x1866, "Data Bus Powertrain Missing messages");
        }
    }
}